#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+    Listens on port 80.
#+    Returns a page containing "Hello World!" when queried
#++    at the root with a curl GET request.

sudo apt-get update
sudo apt-get install -y nginx

sudo mkdir /var/www
sudo touch /var/www/index.html
echo "Hello World!" > /var/www/index.html
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /var/www/html;
     index       index.html;
}
" > /etc/nginx/sites-available/default

sudo service nginx restart
