#!/usrbin/env bash
# Configure Nginx so that its HTTP response contains a custom header

sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'

sudo mkdir /etc/nginx/html
sudo touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html

printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    add_header X-Served-By $HOSTNAME;
    root   /etc/nginx/html;
    index  index.html index.htm;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" > /etc/nginx/sites-available/default

sudo service nginx restart