#!/usr/bin/env bash
# Displays to infinity and beyond indefinitely
# With sleep 2 between each iteration
# And "I am invincible!!!" when recieving a SIGTERM signal

trap "echo 'I am invincible!!!'" SIGTERM
while :; do echo 'To infinity and beyond'; sleep 2; done
